const http = require('http');
const fs = require('fs');
const path = require('path');

const port = process.env.PORT || 3000;
const build = process.env.APP_BUILD || 'local';
const dataDir = fs.existsSync(path.join(__dirname, 'data')) ? path.join(__dirname, 'data') : path.join(__dirname, '..', 'data');
const networkData = {
  passengers: JSON.parse(fs.readFileSync(path.join(dataDir, 'passengers.json'), 'utf8')),
  flights: JSON.parse(fs.readFileSync(path.join(dataDir, 'flights.json'), 'utf8')),
  network: JSON.parse(fs.readFileSync(path.join(dataDir, 'network.json'), 'utf8'))
};

http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SkyBridge Network Recovery Optimizer</title>
  <style>
    :root { --ink:#ecf3ff; --muted:#aabbd5; --panel:#121f36; --line:#2c4164; --blue:#53a9ff; --mint:#4be1b1; --warn:#ffc465; --danger:#ff7184; }
    * { box-sizing:border-box } body { margin:0; background:#091426; color:var(--ink); font-family:Inter, ui-sans-serif,system-ui,-apple-system,sans-serif; }
    main { max-width:1300px; margin:auto; padding:28px; } header { display:flex; justify-content:space-between; gap:18px; align-items:flex-start; margin-bottom:25px }
    h1 { margin:0; font-size:clamp(1.7rem,4vw,2.7rem); letter-spacing:-.05em } h2 { margin:0 0 14px; font-size:1rem } .eyebrow { color:var(--mint); font-weight:700; text-transform:uppercase; letter-spacing:.12em; font-size:.72rem; margin:0 0 8px }
    .build { border:1px solid var(--line); padding:8px 12px; border-radius:20px; color:var(--muted); white-space:nowrap; font-size:.82rem }
    .grid { display:grid; grid-template-columns:1.15fr .85fr; gap:18px }.panel { background:linear-gradient(150deg,#152541,#101c31); border:1px solid var(--line); border-radius:18px; padding:20px; box-shadow:0 16px 35px #02071366 }
    .status { display:flex; align-items:center; gap:9px; color:#ffd28a; margin:7px 0 20px }.dot { width:9px; height:9px; border-radius:50%; background:var(--warn); box-shadow:0 0 12px var(--warn) }
    .route { display:flex; gap:10px; align-items:center; flex-wrap:wrap }.hub { padding:10px 13px; border-radius:10px; background:#193359; border:1px solid #3566a1; font-weight:700 }.arrow { color:var(--blue); font-size:1.25rem }.small { font-size:.84rem; color:var(--muted); line-height:1.55 }
    .metrics { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin-top:20px }.metric { background:#0c182b; border-radius:11px; padding:12px }.metric b { display:block; font-size:1.18rem; margin-top:3px }.metric span { font-size:.72rem; color:var(--muted) }
    .controls { display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-top:13px } label { font-size:.8rem;color:var(--muted) } input { width:100%; accent-color:var(--blue); margin-top:8px } select { margin-top:7px;width:100%;border-radius:8px;border:1px solid var(--line);background:#0b1729;color:var(--ink);padding:9px }
    button { background:linear-gradient(135deg,#308be9,#55b4ff); color:#06152a; border:0; border-radius:10px; padding:12px 15px; font-weight:800; cursor:pointer; margin-top:18px; width:100% } button:hover { filter:brightness(1.1) }
    .full { margin-top:18px }.recommend { border-left:4px solid var(--mint); background:#102d35; padding:15px; border-radius:0 12px 12px 0; margin-bottom:16px }.recommend strong { font-size:1.15rem; display:block }.recommend p { margin:6px 0 0; color:#c2d6e9; font-size:.88rem;line-height:1.45 }.network-map { min-height:270px; border:1px solid #29476d; border-radius:14px; overflow:hidden; background:radial-gradient(circle at 52% 42%,#17345a,#0a172a 72%); }.network-map svg{display:block;width:100%;height:270px}.map-land{fill:#1a3150;stroke:#2b4d76;stroke-width:1}.map-line{fill:none;stroke:#3b5f88;stroke-width:2;stroke-dasharray:5 5;opacity:.8}.map-line.selected{stroke:#55b4ff;stroke-width:4;stroke-dasharray:none;opacity:1}.map-line.risk{stroke:#ff9c6b;stroke-width:4}.map-node circle{fill:#4be1b1;stroke:#d9fff2;stroke-width:2}.map-node.weather circle{fill:#ffc465}.map-node.airspace circle{fill:#ff7184}.map-node text{fill:#ecf3ff;font-size:11px;font-weight:700;text-anchor:middle}.map-node .sub{fill:#aabbd5;font-size:9px;font-weight:500}.map-legend{display:flex;gap:16px;flex-wrap:wrap;margin-top:10px;color:var(--muted);font-size:.75rem}.legend-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px;background:var(--mint)}.weather-dot{background:var(--warn)}.airspace-dot{background:var(--danger)}.route-dot{background:var(--blue)}
    table { width:100%; border-collapse:collapse; font-size:.84rem } th { color:var(--muted); text-align:left; font-weight:600; font-size:.72rem; text-transform:uppercase; letter-spacing:.04em } td,th { padding:11px 8px; border-bottom:1px solid #263b5b } tr.best { background:#123d47 } .cost { font-weight:800 }.tag { padding:3px 7px;border-radius:20px;background:#243752;color:#c9dcf5;font-size:.72rem }.green { color:var(--mint) }.red { color:var(--danger) }
    .passengers { display:grid; grid-template-columns:repeat(2,1fr); gap:10px }.passenger { background:#0d1a2f;border:1px solid #203758;padding:12px;border-radius:11px }.passenger b { font-size:.86rem }.passenger div { margin-top:4px;font-size:.76rem;color:var(--muted) }.priority { color:#ffcf76;font-size:.7rem;text-transform:uppercase;font-weight:800 }.policy { display:grid;grid-template-columns:repeat(3,1fr);gap:10px }.policy div,.fare { background:#0c182b;border:1px solid #263d5d;border-radius:11px;padding:12px }.policy b,.fare b { display:block;margin:4px 0;font-size:1.05rem }.policy small,.fare small { color:var(--muted);line-height:1.35;display:block }.pricegrid { display:grid;grid-template-columns:repeat(7,1fr);gap:7px }.fare { padding:10px 7px }.fare.active { border-color:#4be1b1;background:#10343d }.fare strong { display:block;color:var(--mint);font-size:.92rem }.fare small { font-size:.67rem;margin-top:4px }.horizon { display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px }.horizon span { font-size:.72rem;border-radius:20px;padding:5px 9px;border:1px solid #2f476a;color:var(--muted) }.horizon .active { color:#061b21;background:var(--mint);border-color:var(--mint);font-weight:800 } @media(max-width:800px){.pricegrid{grid-template-columns:repeat(4,1fr)}.policy{grid-template-columns:1fr}}
    footer { color:#8295b2;font-size:.76rem;margin-top:16px;line-height:1.45 }.live { color:var(--mint);font-size:.78rem;margin-top:12px } @media(max-width:800px){.grid{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}.passengers{grid-template-columns:1fr}main{padding:17px}}
  </style>
</head>
<body><main>
  <header><div><p class="eyebrow">Airline Operations Control · Decision-support simulation</p><h1>SkyBridge Network Recovery Optimizer</h1></div><div class="build">Jenkins build ${build}</div></header>
  <section class="grid">
    <div class="panel"><h2>Disruption scenario</h2><div class="status"><i class="dot"></i><b id="scenarioTitle">Forecast disruption at JFK</b></div>
      <div class="route"><span class="hub" id="routeOrigin">SFO</span><span class="arrow">→</span><span class="hub" id="routeHub">JFK · constrained hub</span><span class="arrow">→</span><span class="hub" id="routeConnection">LHR</span><span class="arrow">→</span><span class="hub" id="routeDestination">DEL</span></div>
      <p class="small">The optimizer evaluates an uncertain 2–6 hour weather event, reduced hub capacity, turbulence exposure, passenger connection feasibility, recovery inventory, and downstream revenue.</p><p class="live" id="liveWeather">● Live weather feed: loading…</p>
      <div class="metrics"><div class="metric"><span>Affected flights</span><b id="affectedFlights">—</b></div><div class="metric"><span>Protected itineraries</span><b id="protectedItineraries">—</b></div><div class="metric"><span>High-risk connections</span><b id="highRiskConnections">—</b></div></div>
    </div>
    <div class="panel"><h2>Optimizer settings</h2><div class="controls"><label>Disruption hub<select id="hub"><option>JFK — New York</option><option>ORD — Chicago</option><option>DFW — Dallas/Fort Worth</option><option>LHR — London Heathrow</option><option>DXB — Dubai</option><option>DOH — Doha</option><option>DEL — Delhi</option><option>SIN — Singapore</option><option>HKG — Hong Kong</option><option>NRT — Tokyo Narita</option><option>ICN — Seoul Incheon</option></select></label><label>Monte Carlo trials<select id="trials"><option value="250">250 trials</option><option value="500" selected>500 trials</option><option value="1000">1,000 trials</option></select></label><label>Risk aversion<input id="risk" type="range" min="0" max="1" step=".05" value=".55"><span id="riskLabel">55% tail-risk weight</span></label><label>Weather severity<input id="weather" type="range" min=".35" max="1" step=".05" value=".75"><span id="weatherLabel">75% forecast severity</span></label><label>Airspace/news shock<input id="news" type="range" min="0" max="1" step=".05" value=".2"><span id="newsLabel">20% closure/news shock</span></label></div><button id="run">Run stochastic recovery optimization</button><p class="small">Every run resamples weather duration, connection failures, recovery-seat availability, cancellations, reroutes, and new-demand revenue.</p></div>
  </section>
  <section class="panel full"><h2>Network action recommendation</h2><div class="recommend" id="recommend"><strong>Calculating recovery policy…</strong><p>Run complete results will appear here.</p></div><table><thead><tr><th>Candidate policy</th><th>Expected cost</th><th>95th percentile</th><th>Risk-adjusted score</th><th>Protected itineraries</th><th>Decision</th></tr></thead><tbody id="results"></tbody></table></section>
  <section class="grid full"><div class="panel"><h2>Regulated overbooking & recovery inventory</h2><p class="small">The model protects critical international connections. It seeks volunteers before any involuntary action and prioritizes flexible, local, low-priority itineraries for reaccommodation.</p><div class="policy" id="overbook"></div></div><div class="panel"><h2>7-day recovery & revenue horizon</h2><div class="horizon"><span class="active">0–72 hours · active optimizer</span><span>Days 4–7 · controlled forecast</span></div><p class="small">During the first 72 hours, affected passengers receive fare protection while the system manages holds, rebooking, hotel and recovery seats. Days 4–7 use capped new-sale prices and inventory forecasts.</p><div class="pricegrid" id="pricing"></div></div></section>
  <section class="grid full"><div class="panel"><h2>Multi-leg passenger recovery queue</h2><div class="passengers" id="passengers"></div></div><div class="panel"><h2>How the model is non-linear</h2><p class="small">Missed-connection probability follows an S-curve as delay exceeds available connection time. Compensation rises faster after long delays, hotel cost jumps once overnight recovery is required, and tail-risk penalizes severe scenarios beyond the average.</p><p class="small">This prototype uses stochastic simulation and a non-linear risk-adjusted objective. It is not a production airline dispatch system and uses simulated inventory, passenger, and cost data.</p></div></section>
  <section class="panel full"><h2>Live network disruption map</h2><p class="small">Route legs, hub pressure, weather exposure, and airspace risk update from the controls and forecast feeds.</p><div id="networkMap" class="network-map" aria-label="Interactive airline network map"></div><div class="map-legend"><span><i class="legend-dot weather-dot"></i>Weather exposure</span><span><i class="legend-dot airspace-dot"></i>Airspace/news risk</span><span><i class="legend-dot route-dot"></i>Selected route</span></div></section>
  <footer>Research framing: dynamic disruption management under airport operating uncertainty. This classroom prototype uses simulated data and does not make real flight, pricing, or passenger decisions.</footer>
</main>
<script>
const networkData = ${JSON.stringify(networkData)};
const pax=networkData.passengers.concat([
 ['Elena Rossi','FCO → LHR → JFK → SFO','Business · 3 legs','Critical','Platinum'],['Kenji Sato','NRT → HKG → SYD','Economy · 2 legs','High','Gold'],['Fatima Al-Hassan','DOH → DXB → MEL','Premium · 2 legs','High','Silver'],['Lucas Pereira','GRU → MIA → JFK → LHR','Economy · 3 legs','Medium','None'],['Grace Okafor','ACC → LHR → DEL','Business · 2 legs','Critical','Gold'],['Oliver Smith','LHR → JFK → YYZ','Economy · 2 legs','Medium','Silver'],['Hana Kim','ICN → SIN → AKL','Premium · 2 legs','High','Platinum'],['Mateo Garcia','MAD → CDG → JFK → LAX','Family · 3 legs','Medium','None'],['Nora Williams','MEL → SYD → HKG → SFO','Business · 3 legs','Critical','Gold'],['Arjun Mehta','BOM → DEL → DXB → LHR','Economy · 3 legs','High','Silver'],['Claire Dubois','CDG → LHR → JFK','Premium · 2 legs','High','Platinum'],['Samir Rahman','KUL → SIN → HKG → NRT','Economy · 3 legs','Medium','None']
]);
const legControl=document.createElement('label');legControl.innerHTML='Disrupted legs<select id="legs" multiple size="3"><option value="SFO-JFK" selected>SFO–JFK</option><option value="JFK-LHR" selected>JFK–LHR</option><option value="LHR-DEL">LHR–DEL</option><option value="SIN-HKG">SIN–HKG</option><option value="SYD-AKL">SYD–AKL</option></select>';document.querySelector('.controls').appendChild(legControl);
function renderQueue(severity,news){const rank={Critical:4,High:3,Medium:2,Low:1};const ordered=[...pax].sort((a,b)=>(rank[b[3]]-rank[a[3]])+(Math.random()-.5)*news*2);document.querySelector('#passengers').innerHTML=ordered.map((p,i)=>{const cancelled=(severity+news*.4>.92&&i>4)||(news>.7&&i>5);const action=cancelled?'Cancellation recovery · reaccommodate':(severity>.75?'Tight connection · protect':'Monitor · confirmed');return '<article class="passenger"><span class="priority">'+p[3]+' priority · '+(p[4]||'None')+' loyalty</span><b>'+p[0]+'</b><div>'+p[1]+'</div><div>'+p[2]+' · '+action+'</div></article>'}).join('')}
renderQueue(+document.querySelector('#weather').value,+document.querySelector('#news').value);
const hubCoords={JFK:[40.64,-73.78],ORD:[41.98,-87.90],DFW:[32.90,-97.04],LHR:[51.47,-.45],DXB:[25.25,55.36],DOH:[25.27,51.61],DEL:[28.56,77.10],SIN:[1.36,103.99],HKG:[22.31,113.91],NRT:[35.77,140.39],ICN:[37.46,126.44],SYD:[-33.94,151.18],MEL:[-37.67,144.84],AKL:[-37.01,174.79]};
function updateScenarioTitle(code){document.querySelector('#scenarioTitle').textContent=(code==='DXB'||code==='DOH'?'Airspace and reroute risk forecast at ':'Forecast weather/capacity risk at ')+code}
[['SYD','Sydney'],['MEL','Melbourne'],['AKL','Auckland']].forEach(([code,name])=>{const option=document.createElement('option');option.textContent=code+' — '+name;document.querySelector('#hub').appendChild(option);});
async function updateLiveWeather(){const code=document.querySelector('#hub').value.split(' ')[0],coord=hubCoords[code];document.querySelector('#routeHub').textContent=code+' · constrained hub';try{const fields='temperature_2m,wind_speed_10m,wind_gusts_10m,precipitation,rain,showers,snowfall,weather_code,cloud_cover,cloud_cover_low,cloud_cover_mid,visibility,pressure_msl';const url='https://api.open-meteo.com/v1/forecast?latitude='+coord[0]+'&longitude='+coord[1]+'&current='+fields+'&wind_speed_unit=mph';const data=await fetch(url).then(r=>r.json());const c=data.current||{};const visibilityRisk=Math.max(0,(10000-(c.visibility||10000))/8000),cloudRisk=((c.cloud_cover_low||0)*.55+(c.cloud_cover_mid||0)*.2+(c.cloud_cover||0)*.25)/100,windRisk=(c.wind_gusts_10m||0)/75+(c.wind_speed_10m||0)/100,precipRisk=((c.precipitation||0)+(c.rain||0)+(c.showers||0)*1.4+(c.snowfall||0)*2)/10,pressureRisk=Math.max(0,(1005-(c.pressure_msl||1015))/30),codeRisk=(c.weather_code||0)>=95?.42:(c.weather_code||0)>=80?.25:(c.weather_code||0)>=61?.12:0;const liveRisk=Math.min(1,Math.max(.05,visibilityRisk*.32+cloudRisk*.18+windRisk*.22+precipRisk*.2+pressureRisk*.08+codeRisk));document.querySelector('#weather').value=liveRisk.toFixed(2);document.querySelector('#weatherLabel').textContent=Math.round(liveRisk*100)+'% multi-variable weather risk';document.querySelector('#liveWeather').textContent='● Open-Meteo: '+Math.round(c.temperature_2m||0)+'° · gusts '+Math.round(c.wind_gusts_10m||0)+' mph · visibility '+Math.round((c.visibility||0)/1000)+' km · cloud '+Math.round(c.cloud_cover||0)+'% · precipitation '+(c.precipitation||0)+' mm';run();}catch(e){document.querySelector('#liveWeather').textContent='● Live weather unavailable — using simulated severity';}}
function money(n){return '$'+Math.round(n).toLocaleString()}
function logistic(x){return 1/(1+Math.exp(-x))}
function normal(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
const policies=[
 {name:'Hold 90 minutes',type:'hold',hold:90},{name:'Hold 180 minutes',type:'hold',hold:180},{name:'Cancel + same-day rebook',type:'cancel'},{name:'Overnight protect + hotel',type:'hotel'},{name:'Hybrid: protect long-haul, rebook others',type:'hybrid'}
];
function sample(policy,severity,geopoliticalRisk){
 const duration=Math.max(1.5,2.1+severity*3.4+normal()*.85); const capacity=Math.max(.18,1-severity*.64+normal()*.09); const turbulence=Math.max(.15,severity*.72+normal()*.14); const inventory=Math.max(.12,.61-severity*.25+normal()*.13); const demand=Math.max(.1,.5+normal()*.22); const departureSlots=Math.max(.08,.82-severity*.42+normal()*.12); const arrivalSlots=Math.max(.08,.79-severity*.46+normal()*.12); const slotFeasible=Math.min(departureSlots,arrivalSlots); const curfewRisk=logistic((duration-4.5)*1.3); const slotPenalty=9200*Math.pow(1-slotFeasible,1.55)+4200*curfewRisk;
 let operational=slotPenalty, passenger=0, hotel=0, partner=0, lost=0, recovered=0;
 const classFactor={Economy:1.0,Family:1.05,Premium:1.2,Business:1.35}; const loyaltyFactor={None:1.0,Silver:1.08,Gold:1.16,Platinum:1.25}; const protectionWeight=pax.reduce((sum,p)=>sum+(classFactor[(p[2]||'').split(' ')[0]]||1)*(loyaltyFactor[p[4]]||1),0)/pax.length;
 if(policy.type==='hold'){ const h=policy.hold; operational=5600*Math.pow(h/60,1.35)*(1+.12*duration)+1700*turbulence; const missed=logistic((h-(65+inventory*105))/27); passenger=46*protectionWeight*(110*Math.pow(h/60,1.42)+820*Math.pow(missed,1.35)); hotel=46*missed*logistic((duration-3.8)*1.7)*205; recovered=46*(1-missed*.55); lost=(1-inventory)*19000; }
 if(policy.type==='cancel'){ operational=12400+3300*(1-capacity); const unrebooked=1-inventory*.86; partner=46*inventory*(360+160*turbulence); passenger=46*(unrebooked*1175+230); hotel=46*unrebooked*.45*225; recovered=46*(1-unrebooked); lost=17500*(1-demand*.42); }
 if(policy.type==='hotel'){ operational=8400+1900*duration; hotel=46*235*(1+.18*duration); passenger=46*(420+190*Math.pow(duration,1.25)); recovered=46*.93; lost=13700*(1-demand*.38); }
 if(policy.type==='hybrid'){ const longhaul=18; const shorthaul=28; operational=9750+2900*Math.pow(duration,1.2); const longMiss=logistic((100-(70+inventory*110))/28); const shortUn=1-inventory*.9; passenger=longhaul*(560+850*Math.pow(longMiss,1.4))+shorthaul*(260+980*Math.pow(shortUn,1.25)); hotel=longhaul*longMiss*.52*235; partner=(longhaul*(1-longMiss)+shorthaul*inventory)*310; recovered=longhaul*(1-longMiss*.3)+shorthaul*(1-shortUn); lost=10600*(1-demand*.48); }
 // Lost sales are a benefit: protected passengers consume capacity, but unused recovery seats may sell at a non-linear price.
 const fareMultiplier=1+Math.min(.15,Math.pow(demand,1.35)*.16)-severity*.07;
 const resale=Math.pow(Math.max(0,inventory-.28),1.18)*demand*14200*fareMultiplier;
 // Voluntary offers and compensation rise non-linearly when constrained recovery seats create an overbooking conflict.
 const excess=Math.max(0,16*(1-inventory)-5); const regulatedReaccommodation=560*Math.pow(excess,1.32);
 const geopoliticalPenalty=geopoliticalRisk*(6800+11500*Math.pow(1-inventory,1.25)+4800*curfewRisk);
 const total=operational+passenger+hotel+partner+lost+regulatedReaccommodation+geopoliticalPenalty-resale;
 return {total,recovered};
}
function quantile(a,q){const b=[...a].sort((x,y)=>x-y);return b[Math.floor((b.length-1)*q)]}
function run(){ const trials=+document.querySelector('#trials').value, severity=+document.querySelector('#weather').value, news=+document.querySelector('#news').value, effectiveSeverity=Math.min(1,severity+news*.3), risk=+document.querySelector('#risk').value; updateMetrics(effectiveSeverity); renderQueue(severity,news); renderOverbooking(effectiveSeverity,news); const rows=policies.map(p=>{let vals=[],pro=[];for(let i=0;i<trials;i++){let s=sample(p,effectiveSeverity,news);vals.push(s.total);pro.push(s.recovered)}const mean=vals.reduce((a,b)=>a+b,0)/trials,p95=quantile(vals,.95),tail=vals.filter(x=>x>=p95).reduce((a,b)=>a+b,0)/Math.max(1,vals.filter(x=>x>=p95).length);return {...p,mean,p95,score:mean*(1-risk)+tail*risk,protected:pro.reduce((a,b)=>a+b,0)/trials};}).sort((a,b)=>a.score-b.score);
 const best=rows[0], hub=document.querySelector('#hub').value.split(' ')[0]; document.querySelector('#recommend').innerHTML='<strong>Recommend: '+best.name+'</strong><p>For the '+hub+' disruption scenario, this policy has the lowest risk-adjusted network cost at <b>'+money(best.score)+'</b>. It protects an expected <b>'+best.protected.toFixed(0)+' of 46 itineraries</b> while accounting for severe-delay tail scenarios.</p>';
 document.querySelector('#results').innerHTML=rows.map((r,i)=>'<tr class="'+(!i?'best':'')+'"><td><b>'+r.name+'</b></td><td class="cost">'+money(r.mean)+'</td><td>'+money(r.p95)+'</td><td class="'+(!i?'green':'')+'">'+money(r.score)+'</td><td>'+r.protected.toFixed(1)+' / 46</td><td>'+(i===0?'<span class="tag">Recommended</span>':'<span class="tag">Alternative</span>')+'</td></tr>').join(''); renderPricing(severity); }
 const currentSeverity=+document.querySelector('#weather').value; const volunteer=Math.max(2,Math.round(3+currentSeverity*3-Math.random()*2)), protectedSeats=Math.round(14+currentSeverity*5), standby=Math.max(1,Math.round(7-currentSeverity*3));
 document.querySelector('#overbook').innerHTML='<div><small>1. Protect</small><b>'+protectedSeats+' priority seats</b><small>Multi-leg international, medical, premium and tight-connection passengers cannot be displaced.</small></div><div><small>2. Ask volunteers</small><b>'+volunteer+' offers</b><small>Offer voucher, hotel, or same-day alternate itinerary before any involuntary step.</small></div><div><small>3. Reaccommodate</small><b>'+standby+' flexible guests</b><small>Lowest priority, local, flexible itineraries are ranked for the next safe option; compensation is included.</small></div>';
 function renderOverbooking(severity,geopoliticalRisk){const priority=Math.min(pax.length,Math.round(7+severity*9+geopoliticalRisk*4));const volunteers=Math.max(1,Math.round(8-severity*4-geopoliticalRisk*3));const reaccommodate=Math.max(1,Math.round(3+severity*5+geopoliticalRisk*4));const reason=geopoliticalRisk>.4?'airspace reroute / cancellation exposure':'weather and connection exposure';document.querySelector('#overbook').innerHTML='<div><small>1. Protect</small><b>'+priority+' priority seats</b><small>Cabin, loyalty, multi-leg and critical-connection passengers are protected first.</small></div><div><small>2. Ask volunteers</small><b>'+volunteers+' offers</b><small>Voucher and hotel offers scale with '+reason+'.</small></div><div><small>3. Reaccommodate</small><b>'+reaccommodate+' flexible guests</b><small>Lowest-priority flexible itineraries move to the next safe route; compensation is modeled.</small></div>' }
 function renderPricing(pricingSeverity){ const demandAdjustment=+(document.querySelector('#futureDemand')?.value||.7); const days=['Today','Day 2','Day 3','Day 4','Day 5','Day 6','Day 7']; const base=420; document.querySelector('#pricing').innerHTML=days.map((d,i)=>{const active=i<3;const immediateDemand=Math.max(.65,Math.min(1.5,.78+normal()*.13+demandAdjustment*.45+(pricingSeverity-.55)*.35));const cap=active?1:1.22;const factor=active?1:Math.min(cap,immediateDemand*(1-pricingSeverity*.06));const fare=Math.round(base*factor/5)*5;const rule=active?'Protected recovery fare':'Demand-adjusted new-sale fare';return '<div class="fare '+(active?'active':'')+'"><small>'+d+'</small><strong>'+money(fare)+'</strong><small>'+rule+'</small></div>'}).join(''); }
const scenarioControl=document.createElement('label');scenarioControl.innerHTML='Forecast disruption type<select id="scenarioType"><option value="none">No material disruption</option><option value="weather">Convective weather</option><option value="political">Political / airspace closure</option><option value="ash">Volcanic ash</option><option value="cloud">Low cloud / visibility</option></select>';document.querySelector('.controls').appendChild(scenarioControl);
scenarioControl.style.display='none';document.querySelector('#news').closest('label').style.display='none';const sourceStatus=document.createElement('p');sourceStatus.className='live';sourceStatus.id='sourceStatus';sourceStatus.textContent='● Automatic disruption forecast: collecting weather, news, and ash-advisory signals…';document.querySelector('#liveWeather').after(sourceStatus);
const airportOptions=['AKL','BOM','CDG','DEL','DOH','DXB','HKG','ICN','JFK','LHR','MEL','NRT','SIN','SYD','SFO'];const makeRouteSelect=(id,label,value)=>{const el=document.createElement('label');el.innerHTML=label+'<select id="'+id+'">'+airportOptions.map(a=>'<option '+(a===value?'selected':'')+'>'+a+'</option>').join('')+'</select>';document.querySelector('.controls').appendChild(el)};makeRouteSelect('origin','Route origin','SFO');makeRouteSelect('connection','Connection after hub','LHR');makeRouteSelect('destination','Final destination','DEL');function updateRoute(){document.querySelector('#routeOrigin').textContent=document.querySelector('#origin').value;document.querySelector('#routeConnection').textContent=document.querySelector('#connection').value;document.querySelector('#routeDestination').textContent=document.querySelector('#destination').value}
function updateMetrics(severity){const hub=document.querySelector('#hub').value.split(' ')[0],route=[document.querySelector('#origin').value,hub,document.querySelector('#connection').value,document.querySelector('#destination').value],selected=[...document.querySelector('#legs').selectedOptions].map(o=>o.value.replace('-', ' → '));const routeHits=pax.filter(p=>route.some(a=>p[1].includes(a))).length;const highRisk=pax.filter(p=>route.some(a=>p[1].includes(a))&&(['Critical','High'].includes(p[3]))).length;const affectedFlights=Math.max(1,selected.length*2+Math.round(severity*6));const protectedCount=Math.min(pax.length,Math.max(routeHits,Math.round(routeHits+severity*4)));document.querySelector('#affectedFlights').textContent=affectedFlights;document.querySelector('#protectedItineraries').textContent=protectedCount;document.querySelector('#highRiskConnections').textContent=Math.min(protectedCount,Math.max(highRisk,Math.round(highRisk+severity*3)))}
const futureControl=document.createElement('label');futureControl.innerHTML='Days 4–7 demand forecast<input id="futureDemand" type="range" min="0" max="1" step=".05" value=".7"><span id="futureDemandLabel">70% expected last-minute demand</span>';document.querySelector('.horizon').after(futureControl);
futureControl.style.display='none';const fareForecast=document.createElement('p');fareForecast.className='small';fareForecast.id='fareForecast';fareForecast.textContent='Automatic days 4–7 demand and fare forecast: waiting for risk signals…';document.querySelector('.horizon').after(fareForecast);const airspaceMonitor=document.createElement('p');airspaceMonitor.className='live';airspaceMonitor.id='airspaceMonitor';airspaceMonitor.textContent='● Airspace monitor: evaluating closure, conflict, and rerouting news signals…';document.querySelector('#sourceStatus').after(airspaceMonitor);
function updateScenario(){const code=document.querySelector('#hub').value.split(' ')[0],type=document.querySelector('#scenarioType').value,labels={none:'No material disruption signal',weather:'Forecast weather/capacity risk',political:'Anticipated political airspace-closure risk',ash:'Forecast volcanic-ash route risk',cloud:'Forecast low-cloud / visibility risk'};document.querySelector('#scenarioTitle').textContent=labels[type]+' at '+code;const shock={none:.05,weather:.2,political:.75,ash:.85,cloud:.45}[type];document.querySelector('#news').value=shock;document.querySelector('#newsLabel').textContent=Math.round(shock*100)+'% anticipated disruption risk';run()}
async function autoForecast(){const code=document.querySelector('#hub').value.split(' ')[0];let political=0,ash=0,headlines=[];try{const query=encodeURIComponent('airspace closure OR flight cancellation OR aviation disruption '+code);const articles=await fetch('https://api.gdeltproject.org/api/v2/doc/doc?query='+query+'&mode=artlist&format=json&maxrecords=10').then(r=>r.json());political=Math.min(1,((articles.articles||[]).length/10));headlines=(articles.articles||[]).slice(0,2).map(a=>a.title).filter(Boolean);}catch(e){}try{const advisory=await fetch('https://ospo.noaa.gov/products/atmosphere/vaac/messages.html').then(r=>r.text());ash=/ash advisory|volcanic ash/i.test(advisory)?0.35:0;}catch(e){}const weather=+document.querySelector('#weather').value;const type=ash>.6?'ash':political>.55?'political':weather>.65?'weather':weather>.5?'cloud':'none';document.querySelector('#scenarioType').value=type;const risk=Math.max({none:.05,weather:weather,political:political,ash:ash,cloud:Math.max(.25,weather*.7)}[type],.05);const demandForecast=Math.min(.95,Math.max(.35,.52+political*.28+weather*.12+ash*.22));document.querySelector('#futureDemand').value=demandForecast;document.querySelector('#futureDemandLabel').textContent=Math.round(demandForecast*100)+'% predicted last-minute demand';document.querySelector('#fareForecast').textContent='Automatic days 4–7 demand forecast: '+Math.round(demandForecast*100)+'% based on weather, airspace, ash, and disruption-driven rebooking demand.';document.querySelector('#news').value=risk;updateScenario();document.querySelector('#sourceStatus').textContent='● Automatic forecast: weather '+Math.round(weather*100)+'% · news/airspace '+Math.round(political*100)+'% · volcanic ash '+Math.round(ash*100)+'% — dominant risk: '+type;document.querySelector('#airspaceMonitor').textContent=political>.15?'● Airspace monitor: '+Math.round(political*100)+'% closure/reroute risk'+(headlines.length?' · '+headlines.join(' | '):''):'● Airspace monitor: no material closure or rerouting signal for '+code;}
document.querySelector('#run').onclick=run;document.querySelector('#hub').onchange=()=>{updateLiveWeather();autoForecast()};document.querySelector('#futureDemand').oninput=e=>{document.querySelector('#futureDemandLabel').textContent=Math.round(e.target.value*100)+'% expected last-minute demand';renderPricing(+document.querySelector('#weather').value)};document.querySelector('#risk').oninput=e=>document.querySelector('#riskLabel').textContent=Math.round(e.target.value*100)+'% tail-risk weight';document.querySelector('#weather').oninput=e=>document.querySelector('#weatherLabel').textContent=Math.round(e.target.value*100)+'% forecast severity';updateLiveWeather();autoForecast();
['origin','connection','destination'].forEach(id=>document.querySelector('#'+id).onchange=()=>{updateRoute();run()});updateRoute();
</script><script>
function renderNetworkMap(){const hub=document.querySelector('#hub').value.split(' ')[0],route=[document.querySelector('#origin')?.value||'SFO',hub,document.querySelector('#connection')?.value||'LHR',document.querySelector('#destination')?.value||'DEL'],points={SFO:[12,58],JFK:[38,42],LHR:[51,31],DXB:[65,51],DEL:[72,48],SIN:[78,67],HKG:[84,55],NRT:[88,35],ICN:[87,29],SYD:[91,82],MEL:[87,91],AKL:[97,92]};const xy=a=>{const p=points[a]||[50,50];return[p[0]*10,p[1]*2.5]};let svg='<svg viewBox="0 0 1000 250"><path class="map-land" d="M30 90 Q170 30 300 70 T540 65 T760 75 T980 110 L960 225 Q780 205 650 220 T350 210 T30 220 Z"/>';for(let i=0;i<route.length-1;i++){const p=xy(route[i]),q=xy(route[i+1]);svg+='<path class="map-line selected" d="M '+p[0]+' '+p[1]+' Q '+((p[0]+q[0])/2)+' '+(Math.min(p[1],q[1])-25)+' '+q[0]+' '+q[1]+'"/>'}route.forEach(code=>{const p=xy(code),kind=code===hub?(+document.querySelector('#news').value>.35?'airspace':'weather'):'';svg+='<g class="map-node '+kind+'"><circle cx="'+p[0]+'" cy="'+p[1]+'" r="7"/><text x="'+p[0]+'" y="'+(p[1]-12)+'">'+code+'</text><text class="sub" x="'+p[0]+'" y="'+(p[1]+21)+'">'+(code===hub?'forecast risk':'route')+'</text></g>'});document.querySelector('#networkMap').innerHTML=svg+'</svg>'}setInterval(renderNetworkMap,1200);renderNetworkMap();
</script><script>
function renderNetworkMap(){const hub=document.querySelector('#hub').value.split(' ')[0],route=[document.querySelector('#origin')?.value||'SFO',hub,document.querySelector('#connection')?.value||'LHR',document.querySelector('#destination')?.value||'DEL'],weather=+document.querySelector('#weather').value,news=+document.querySelector('#news').value;const pts={SFO:[12,55],JFK:[28,40],ORD:[25,32],DFW:[24,55],MIA:[26,70],LHR:[49,34],CDG:[51,38],FCO:[54,43],MAD:[46,46],ACC:[47,67],DXB:[64,54],DOH:[63,60],DEL:[72,49],BOM:[69,59],SIN:[78,67],KUL:[77,72],HKG:[84,56],NRT:[89,35],ICN:[87,29],SYD:[91,82],MEL:[87,91],AKL:[97,92]};const xy=c=>{const p=pts[c]||[50,50];return[p[0]*10,p[1]*2.5]};let svg='<svg viewBox="0 0 1000 250" preserveAspectRatio="none"><path class="map-land" d="M20 88 Q120 35 240 63 T430 60 Q530 30 650 67 T830 60 Q930 74 990 112 L965 225 Q850 205 710 220 T455 211 Q300 225 165 209 T20 220 Z"/><path class="map-line" d="M0 80 H1000 M0 140 H1000 M0 200 H1000" style="opacity:.18;stroke-dasharray:2 8"/>';for(let i=0;i<route.length-1;i++){const a=xy(route[i]),b=xy(route[i+1]);svg+='<path class="map-line selected" d="M '+a[0]+' '+a[1]+' Q '+((a[0]+b[0])/2)+' '+(Math.min(a[1],b[1])-28)+' '+b[0]+' '+b[1]+'"/>'}Object.entries(pts).forEach(([code,p0])=>{const p=xy(code),risk=code===hub?Math.max(weather,news):Math.max(.08,((code.charCodeAt(0)+code.charCodeAt(code.length-1))%35)/100+news*.35),kind=risk>.55?'airspace':risk>.3?'weather':'';svg+='<g class="map-node '+kind+'"><circle cx="'+p[0]+'" cy="'+p[1]+'" r="'+(route.includes(code)?8:5)+'"/><text x="'+p[0]+'" y="'+(p[1]-10)+'">'+code+'</text><text class="sub" x="'+p[0]+'" y="'+(p[1]+18)+'">'+Math.round(risk*100)+'% risk</text></g>'});document.querySelector('#networkMap').innerHTML=svg+'</svg>'}renderNetworkMap();
</script></body></html>`);
}).listen(port, () => console.log(`Listening on ${port}`));
